#---XMage Properties---
#Mon Jul 13 16:16:47 PDT 2026
java.version=
xmage.client.console=true
xmage.launcher.version=0.3.8
xmage.launcher.guisize=16
xmage.client.javaopts=-Xmx2000m -Djava.net.preferIPv4Stack\=true -Dfile.encoding\=UTF-8 -Dsun.jnu.encoding\=UTF-8
xmage.home=https\://xmage.today/
xmage.version=1.4.60-dev (2026-06-28 13-19)
xmage.server.console=true
xmage.server.javaopts=-Xmx1G -XX\:MaxPermSize\=384m
xmage.torrent.downrate=0
xmage.torrent.uprate=50
xmage.torrent.use=false
